import { useState, useRef } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { useAvailableDates, useTimeSlots } from "@/hooks/useAvailability";
import { useCreateReservation } from "@/hooks/useReservation";
import { Section, SectionLabel } from "@/components/ui/Section";
import { formatDate, formatTime, cn } from "@/lib/utils";
import { Calendar, Clock, Users, User, Check, ChevronLeft, MapPin } from "lucide-react";
import type { ReservationInsert, ReservationLocationPreference } from "@/types/database";

type Step = 1 | 2 | 3 | 4 | 5;
const GUEST_OPTIONS = [1, 2, 3, 4, 5, 6, 7, 8];
const LOCATION_OPTIONS: { id: ReservationLocationPreference; label: string; desc: string }[] = [
  { id: "interieur", label: "Intérieur", desc: "Salle principale" },
  { id: "terrasse", label: "Terrasse", desc: "Selon météo" },
  { id: "indifferent", label: "Peu importe", desc: "Meilleure place disponible" },
];
const slide = { enter: { opacity: 0, x: 24 }, center: { opacity: 1, x: 0 }, exit: { opacity: 0, x: -24 } };

function StepBar({ current }: { current: Step }) {
  const steps = [{ id: 1, icon: Calendar, label: "Date" }, { id: 2, icon: Clock, label: "Heure" }, { id: 3, icon: Users, label: "Personnes" }, { id: 4, icon: User, label: "Infos" }] as const;
  return <div className="flex items-center mb-10 md:mb-14">{steps.map((s,i)=>{ const Icon=s.icon; const done=current>s.id; const active=current===s.id; return <div key={s.id} className="flex items-center flex-1 last:flex-none"><div className="flex flex-col items-center gap-1.5"><div className={cn("w-9 h-9 flex items-center justify-center border transition-all duration-300", done?"bg-or border-or text-void":active?"border-or text-or":"border-pierre/20 text-pierre/30")}>{done?<Check size={14}/>:<Icon size={14}/>}</div><span className={cn("text-[10px] tracking-wider uppercase hidden sm:block", active?"text-or":"text-pierre/30")}>{s.label}</span></div>{i<steps.length-1&&<div className={cn("flex-1 h-px mx-2 transition-colors duration-500", current>s.id?"bg-or/40":"bg-pierre/10")}/>}</div>})}</div>;
}
function Field({ type="text", placeholder, value, onChange, required }: { type?: string; placeholder: string; value: string; onChange: (v:string)=>void; required?: boolean }) { return <input type={type} placeholder={placeholder} value={value} onChange={e=>onChange(e.target.value)} required={required} autoComplete={type==="email"?"email":type==="tel"?"tel":"off"} className="w-full bg-transparent border border-pierre/20 px-4 py-3 text-creme placeholder:text-pierre/30 focus:border-or/60 outline-none transition-colors text-sm"/>; }

export default function ReservationPage() {
  const [step,setStep]=useState<Step>(1); const [date,setDate]=useState<string|null>(null); const [time,setTime]=useState<string|null>(null); const [guests,setGuests]=useState(2); const [location,setLocation]=useState<ReservationLocationPreference>("indifferent");
  const [contact,setContact]=useState({ firstName:"", lastName:"", email:"", phone:"", notes:"" }); const submitting=useRef(false);
  const { data: availableDates, isLoading: datesLoading } = useAvailableDates(); const { data: slots, isLoading: slotsLoading } = useTimeSlots(date); const mutation=useCreateReservation();
  const datesByMonth: Record<string,string[]> = {}; (availableDates??[]).forEach(d=>{ const key=d.slice(0,7); if(!datesByMonth[key]) datesByMonth[key]=[]; datesByMonth[key].push(d); });
  const canSubmit = contact.firstName.trim() && contact.lastName.trim() && contact.email.trim() && contact.phone.trim();
  async function handleSubmit(){ if(!date||!time||!canSubmit||submitting.current)return; submitting.current=true; const payload:ReservationInsert={ first_name:contact.firstName.trim(), last_name:contact.lastName.trim(), email:contact.email.trim(), phone:contact.phone.trim(), reservation_date:date, reservation_time:time, guests:Number(guests), location_preference:location, notes:contact.notes.trim()||undefined }; try{ await mutation.mutateAsync(payload); setStep(5);}finally{submitting.current=false;} }

  return <><div className="relative h-[40vh] min-h-[300px] flex items-end overflow-hidden"><div className="absolute inset-0 bg-cover bg-center" style={{backgroundImage:"url(https://images.unsplash.com/photo-1550966871-3ed3cdb51f3a?w=1920&q=80)"}}/><div className="absolute inset-0 bg-gradient-to-t from-void via-void/70 to-void/20"/><div className="relative z-10 max-w-7xl mx-auto px-4 sm:px-6 pb-10 w-full"><SectionLabel>Réservation</SectionLabel><h1 className="font-display text-4xl sm:text-5xl md:text-6xl text-creme">Votre table</h1></div></div><Section className="pt-8 pb-20"><div className="max-w-xl mx-auto w-full">{step<5&&<StepBar current={step}/>} {step>1&&step<5&&<button onClick={()=>setStep((s)=>(s-1) as Step)} className="flex items-center gap-1.5 text-pierre/50 text-xs uppercase tracking-wider hover:text-creme transition-colors mb-8"><ChevronLeft size={14}/> Retour</button>}<AnimatePresence mode="wait">
    {step===1&&<motion.div key="s1" variants={slide} initial="enter" animate="center" exit="exit" transition={{duration:.25}}><h2 className="font-display text-2xl sm:text-3xl text-creme mb-2">Choisissez une date</h2><p className="text-pierre/50 text-sm mb-8">Disponibilités sur les 30 prochains jours.</p>{datesLoading?<div className="flex justify-center py-16"><div className="spinner"/></div>:Object.keys(datesByMonth).length===0?<p className="text-pierre/40 text-center py-12">Aucune disponibilité pour le moment.</p>:Object.entries(datesByMonth).map(([monthKey,dates])=>{ const label=new Intl.DateTimeFormat("fr-FR",{month:"long",year:"numeric"}).format(new Date(monthKey+"-02")); return <div key={monthKey} className="mb-8"><p className="text-or text-xs tracking-[0.15em] uppercase mb-3 capitalize">{label}</p><div className="grid grid-cols-4 sm:grid-cols-5 md:grid-cols-7 gap-1.5">{dates.map(d=>{ const dt=new Date(d+"T12:00:00"); return <button key={d} onClick={()=>{setDate(d);setTime(null);setStep(2);}} className={cn("flex flex-col items-center py-2.5 px-1 border text-center transition-all duration-200", date===d?"border-or bg-or/10 text-or":"border-pierre/10 text-creme/70 hover:border-or/40 hover:text-creme")}><span className="text-[10px] uppercase tracking-wide opacity-60">{dt.toLocaleDateString("fr-FR",{weekday:"short"})}</span><span className="text-base font-display mt-0.5">{dt.toLocaleDateString("fr-FR",{day:"numeric"})}</span></button>})}</div></div>})}</motion.div>}
    {step===2&&date&&<motion.div key="s2" variants={slide} initial="enter" animate="center" exit="exit" transition={{duration:.25}}><h2 className="font-display text-2xl sm:text-3xl text-creme mb-2">Choisissez l'heure</h2><p className="text-pierre/50 text-sm mb-8 capitalize">{formatDate(date)}</p>{slotsLoading?<div className="flex justify-center py-16"><div className="spinner"/></div>:<>{["12","19"].map(prefix=>{ const group=(slots??[]).filter(s=>s.slot_time.startsWith(prefix)); if(!group.length)return null; return <div key={prefix} className="mb-8"><p className="text-or text-xs tracking-[0.15em] uppercase mb-3">{prefix==="12"?"Service du midi":"Service du soir"}</p><div className="grid grid-cols-3 sm:grid-cols-4 gap-2">{group.map(slot=><button key={slot.id} disabled={!slot.is_open||slot.available_tables<=0} onClick={()=>{setTime(slot.slot_time);setStep(3);}} className={cn("py-4 border text-sm transition-all", time===slot.slot_time?"border-or bg-or/10 text-or":"border-pierre/10 text-creme/70 hover:border-or/40", (!slot.is_open||slot.available_tables<=0)&&"opacity-30 cursor-not-allowed")}><span className="font-display text-lg">{formatTime(slot.slot_time)}</span></button>)}</div></div>})}</>}</motion.div>}
    {step===3&&<motion.div key="s3" variants={slide} initial="enter" animate="center" exit="exit" transition={{duration:.25}}><h2 className="font-display text-2xl sm:text-3xl text-creme mb-2">Combien de personnes ?</h2><p className="text-pierre/50 text-sm mb-8">Choisissez le nombre de personnes à table et votre préférence de placement.</p><div className="grid grid-cols-4 gap-2 mb-8">{GUEST_OPTIONS.map(n=><button key={n} onClick={()=>setGuests(n)} className={cn("py-4 border font-display text-xl transition-all", guests===n?"border-or bg-or/10 text-or":"border-pierre/10 text-creme/70 hover:border-or/40")}>{n}</button>)}</div><div className="mb-8"><div className="flex items-center gap-2 text-or text-xs uppercase tracking-[0.16em] mb-3"><MapPin size={14}/> Préférence</div><div className="grid sm:grid-cols-3 gap-2">{LOCATION_OPTIONS.map(opt=><button key={opt.id} onClick={()=>setLocation(opt.id)} className={cn("border p-4 text-left transition-all", location===opt.id?"border-or bg-or/10 text-or":"border-pierre/10 text-creme/70 hover:border-or/40")}><span className="block font-display text-xl">{opt.label}</span><span className="block text-[11px] text-pierre/45 mt-1">{opt.desc}</span></button>)}</div></div><button onClick={()=>setStep(4)} className="w-full bg-or text-void py-3 uppercase tracking-[0.18em] text-xs font-medium">Continuer</button></motion.div>}
    {step===4&&<motion.div key="s4" variants={slide} initial="enter" animate="center" exit="exit" transition={{duration:.25}}><h2 className="font-display text-2xl sm:text-3xl text-creme mb-2">Vos coordonnées</h2><p className="text-pierre/50 text-sm mb-8">Dernière étape avant confirmation.</p><div className="space-y-3"><div className="grid sm:grid-cols-2 gap-3"><Field placeholder="Prénom" value={contact.firstName} onChange={v=>setContact({...contact,firstName:v})} required/><Field placeholder="Nom" value={contact.lastName} onChange={v=>setContact({...contact,lastName:v})} required/></div><Field type="email" placeholder="Email" value={contact.email} onChange={v=>setContact({...contact,email:v})} required/><Field type="tel" placeholder="Téléphone" value={contact.phone} onChange={v=>setContact({...contact,phone:v})} required/><textarea placeholder="Message ou demande particulière" value={contact.notes} onChange={e=>setContact({...contact,notes:e.target.value})} rows={4} className="w-full bg-transparent border border-pierre/20 px-4 py-3 text-creme placeholder:text-pierre/30 focus:border-or/60 outline-none transition-colors text-sm"/></div><div className="border border-pierre/10 bg-void-light p-4 mt-6 text-sm text-pierre/60"><p><strong className="text-creme">Résumé :</strong> {date&&formatDate(date)} · {time&&formatTime(time)} · {guests} personne{guests>1?"s":""} · {LOCATION_OPTIONS.find(o=>o.id===location)?.label}</p></div>{mutation.isError&&<p className="text-red-400 text-sm mt-4">Erreur lors de l’envoi. Réessayez.</p>}<button onClick={handleSubmit} disabled={!canSubmit||mutation.isPending} className="w-full mt-6 bg-or text-void py-3 uppercase tracking-[0.18em] text-xs font-medium disabled:opacity-50">{mutation.isPending?"Envoi...":"Confirmer la réservation"}</button></motion.div>}
    {step===5&&<motion.div key="s5" variants={slide} initial="enter" animate="center" exit="exit" transition={{duration:.25}} className="text-center py-8"><div className="w-14 h-14 border border-or bg-or/10 text-or flex items-center justify-center mx-auto mb-6"><Check size={24}/></div><h2 className="font-display text-3xl text-creme mb-3">Demande envoyée</h2><p className="text-pierre/50 text-sm leading-relaxed">Votre demande de réservation a bien été transmise. L’équipe Héritage vous confirmera la table rapidement.</p></motion.div>}
  </AnimatePresence></div></Section></>;
}
